bullet-train-co/bullet_train-base

lib/tasks/bullet_train_tasks.rake, package.json, yarn.lock
Related: https://github.com/bullet-train-co/bullet_train-base/issues/29
* Replace `yarn build --watch` with a new `yarn watch` that rebuilds the outputs on change and updates all local projects linked to this package using `yalc link`, a better alternative to `yarn link`.
* Update `bin/develop` to use `yalc link` and new `yarn watch` scripts in downstream npm packages.
`yalc link` simulates a local npm directory and `yarn push` updates all local installs with the newly-built outputs.
=> Use yalc link instead of yarn link to ensure dependencies work in upstream project

docs/super-scaffolding.md
These are the docs for the feature that closes [this issue](https://github.com/bullet-train-co/bullet_train-super_scaffolding/issues/15).
I'm not sure if adding `readonly` to `trix_editor` here is ideal, but I wanted to stay consistent with the example we use in `crud-field`. I'll update it with something else if using something like `text_field` makes more sense.
=> Add docs for crud-field readonly option

lib/tasks/bullet_train_tasks.rake
Closes [bullet_train#239](https://github.com/bullet-train-co/bullet_train/issues/239)
You can test the Gitpod workspace by putting this link in the browser:
`gitpod.io/#https://github.com/gazayas/bullet_train/tree/features/bin-develop-with-gitpod`
Looks like this:
=> Clone git repositories in `bin/resolve` with Gitpod

app/controllers/sessions_controller.rb, app/views/account/onboarding/user_details/edit.html.erb
Fix the [sign out issue from a while back](https://github.com/bullet-train-co/bullet-train-tailwind-css/issues/395) on the onboarding step.
I wasn't experiencing the same problem in the original issue. This was most likely because I was mainly checking things in Firefox back then, but I’ve been using Chrome mostly now, and I ran into the same issue recently which led me to work on this. 
When first inspecting the issue, I was getting this in my logs:
```
ActionController::RoutingError (No route matches [GET] "/sw.js")
```
Looking into it, I found [this Stack Overflow post](https://stackoverflow.com/questions/56939942/how-to-fix-routingerror-for-a-get-request-looking-for-a-file-sw-js). I also found [this Rails issue](https://github.com/rails/rails/issues/37570) where someone mentions the …
=> Fix sign out logic on user details onboarding page

app/controllers/concerns/controllers/base.rb
I thought through this one a bit and as far as I can tell, I don't think we need any other checks to make sure `current_team` is okay.
I wonder if we had this line in place because of how we handled `current_team` in the original `bullet-train`. Either way, I confirmed that `current_team` stays the same after trying to access a restricted page and being redirected to the dashboard.
This new redirect will take the user to their `Team#index` page.
=> Redirect users to their dashboard when access denied

docs/super-scaffolding/delegated-types.md
Addresses the first TODO in the delegated types docs:
https://github.com/bullet-train-co/bullet_train-base/blob/main/docs/super-scaffolding/delegated-types.md
I'm not sure if this is what was intended by a live example, but the docs themselves were actually pretty easy to follow and I got the delegated types forms working pretty easily.
I did however try to add a picture to the docs, which I couldn't get to display properly:
If I'm missing something though, I'd be glad to adjust the docs accordingly.
=> Write more specific information in delegated types docs

docs/field-partials.md
I remember having a hard time figuring out what data types to use for which partials when I first got started (although most of them take strings), so I think having this in the docs will be helpful (I find myself looking at the Super Scaffolding system test bin setup script if I forget).
=> Add data types to field partial docs

app/models/concerns/records/base.rb
Closes #90.
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/339
We can now put something like the code in the issue to see if a developer is seeding the model or not when running a callback.
=> Add method to check if model is currently seeding

app/javascript/controllers/index.js, app/javascript/controllers/select_all_controller.js
Closes https://github.com/bullet-train-co/bullet_train-fields/issues/20
Co-dependent PRs:
* https://github.com/bullet-train-co/bullet_train-fields/pull/29
* https://github.com/bullet-train-co/bullet_train-themes-tailwind_css/pull/14
This PR adds a global `select-all` Stimulus controller.
A separate PR will deal with removing the select-all functionality from `bulk-actions`, probably at the same time as we remove it in favour of a new npm package for action-models.
=> Add select-all controller

app/helpers/account/teams_helper.rb
Addresses the TODO in `app/helpers/account/teams_helper.rb`
I found this one to be difficult because of the resources we have available. The only one that I could see making the most sense to include here was `@team`, and even then it's not available in all contexts (i.e. - it's `@teams` instead for the index action).
Here is another line that I considered using:
```ruby
@team || @child_object&.team || @parent_object&.team || current_user&.current_team
```
In this case we would prioritize the objects provided in the controller, but ultimately fall back on the `current_user` object if none of them are available.
In the meantime I've left the TODO comment as is in case we wanted to approach the issue in another way.
=> Use `@team` when available in `current_team` helper

lib/tasks/bullet_train_tasks.rake
Closes #145
```
> bin/develop --link super_scaffolding api
```
Running this command will automatically setup a developer's local repositories for `bullet_train-super_scaffolding` and `bullet_train-api` if they have already cloned them via `bin/develop`
```
> bin/develop --reset super_scaffolding api
```
This will revert the Gemfile's changes back to its original state for the selected packages only, and will also run `bundle install`.
I haven't gotten to the Stimulus controllers yet like I mentioned in #145, but I'd like to look into it sometime soon.
=> Add `--link` and `--reset` flags to `bin/develop`

app/controllers/concerns/documentation_support.rb, lib/bullet_train.rb
Closes #138.
If we don't set a valid URL to `ENV['BASE_URL']`, the `default_url_options_from_base_url` method returns an empty hash so our `config/environment/` files don't receive the correct values.
Also, Render generates a Random value for `BASE_URL`, so our code doesn't raise the first error we already had present in the method. Instead of editing that if statement, I figured we could just check if the hash is empty at the end and raise an error since the host, etc. aren't present.
=> Raise error when BASE_URL isn't correctly configured

.circleci/config.yml, .circleci/matching_branch_check
Closes #135
This PR clones the starter repo from a matching branch if it exists. If not, the branch is pulled from the developer's `main` branch.
The only pitfall I can see with this is if the developer hasn't updated their `main` branch. We can definitely default to `bullet-train-co/bullet_train` if there's not matching branch, but I have it cloning from the developer's repository for now.
Either way, you can see that this works because the text added in https://github.com/bullet-train-co/bullet_train/pull/499 shows up in the unit tests here:
=> Clone from matching branch in starter repo in CI

app/views/account/memberships/_index.html.erb, app/views/account/memberships/_membership.html.erb, app/views/account/memberships/index.html.erb, app/views/account/teams/_index.html.erb, app/views/account/teams/_team.html.erb, app/views/account/teams/index.html.erb
Closes #129.
To explain, I'll use the `Membership` model.
When rendering views from a collection (`<%= render @memberships %>`), there are three things that Rails does:
1. Looks for the partial `memberships/membership` to render.
2. Takes that partial and renders it per each object (i.e. renders the same partial 3 times if the collection's size is 3).
3. Gives each iteration of the partial a local called `membership`.
When using the vanilla Rails scaffolder, it automatically creates this file for us. For example, if we scaffold a model called `Foo` this file will also be generated: `app/views/foos/_foo.html.erb`. However, this file doesn't exist for any of our models in Bullet Train.
When scaffolding a model with vanilla Rails, it will generate an index page, but it doesn't generate an …
=> Enable collection rendering

app/helpers/concerns/helpers/base.rb
Addresses the TODO in `app/helpers/concerns/helpers/base.rb`
Joint PR
- https://github.com/bullet-train-co/bullet_train-api/pull/33
This is the only other file I know that calls this method, and although the local tests pass I want to check the tests here too:
https://github.com/bullet-train-co/bullet_train-super_scaffolding/blob/39f5e6c78f3d1512d4cb097781f010e39ec9b120/app/views/api/v1/scaffolding/completely_concrete/tangible_things/index.json.jbuilder
I'll mark it as ready for review if everything's clear there.
Besides that, moving `to_json_api` wasn't so simple. If everything's clear here, I'll look more into moving that method as well.
=> Move `render_pagination` to `bullet_train-api`

docs/themes.md
I noticed our themes docs were outdated when someone asked me about `app/helpers/theme_helper.rb`. I'm sure there's more we could say here, but I at least wrote down the basics so our developers don't get confused when referring to the docs.
I could also see us writing a list of the different available components (like `shared/fields/text_field`) since we don't have a folder in the root directory for the developers to refer to.
=> Update the themes docs

app/models/concerns/users/base.rb
These methods are handled by the roles gem and shouldn't be redefined here.
The RP here https://github.com/bullet-train-co/bullet_train-roles/pull/20 makes some changes to these methods and can't be merged until this conflict is resolved.
=> Remove methods that are now provided by the roles gem

app/helpers/account/dates_helper.rb, config/locales/en/base.yml
Joint PRs
- https://github.com/bullet-train-co/bullet_train-api/pull/29
- https://github.com/bullet-train-co/bullet_train-themes/pull/20
Before, if an object's `Date` or `DateTime` was `nil`, we wouldn't display anything. This adds a locale so we can show a default message instead.
When rendering the partial, we can pass a local called `default_message` to use a message of our own instead of `Never`:
```ruby
<%= render 'shared/attributes/date_and_time', attribute: :last_used_at, default_message: t('custom_message') %>
```
=> Add locale for default `Date` and `DateTime`

lib/bullet_train/resolver.rb
Closes #114.
Whenever the partial resolver couldn't find the file passed by the developer, we would just get the partial resolver template itself:
```
app/views/bullet_train/partial_resolver.html.erb
```
Instead of just returning this string, I typed out a message telling the developer to make sure they have the package name in the string to help us resolve it for them, or they could use the `--interactive` flag and pass the annotated path (in case they weren't aware of it already).
With that being said, if the developer passes the entire path starting from the package name, we can grab the package with the bundler so I added this feature to the script:
```
> bin/resolve bullet_train-themes-1.0.23/app/views/themes/base/attributes/_code.html.erb
Absolute path: …
```
=> Add error handling for unresolved partials, resolve partials with literal path strings

app/views/devise/registrations/new.html.erb
The OAuth link for signing in was outside of the standard form in `sessions#new` which wasn't a problem, but the OAuth link for signing <i>up</i> was <b>inside</b> the form for `registrations#new`, so I moved it outside similar to the `sessions#new` page.
=> Put OAuth sign up link outside of standard sign up form

app/controllers/sessions_controller.rb, app/views/devise/sessions/new.html.erb
Fixes: https://github.com/bullet-train-co/bullet_train/issues/384
=> Disable Turbo on the sign in form when user_return_to points to an oauth path

app/views/layouts/docs.html.erb, docs/application-options.md, docs/index.md
I thought it would be helpful if we had a list of the different environment variables available in case developers wanted to know what they can turn on/off without having to refer to the helper methods in `bullet_train-base`.
I don't think this covers everything, but I left out `DEMO` on purpose because it seems like we only have that available for the original repository.
Also, I split this into two tables because of our current styling. The excess text overflowed off to the right, so I just figured having another table for now would be easiest to manage until we change the style if need be.
=> Add Application Options docs
